valid_comb = [
    # Substance Use
    ["Alcohol_use", "Substance_use_status"],
    ["Substance_use_status", "Alcohol_freq"],
    ["Substance_use_status", "Alcohol_other"],
    ["Substance_use_status", "Alcohol_type"],
    ["Drug_use", "Substance_use_status"],
    ["Substance_use_status", "Drug_freq"],
    ["Substance_use_status", "Drug_other"],
    ["Substance_use_status", "Drug_type"],
    ["Tobacco_use", "Substance_use_status"],
    ["Substance_use_status", "Smoking_freq_other"],
    ["Substance_use_status", "Smoking_freq_ppd"],
    ["Substance_use_status", "Smoking_freq_py"],
    ["Substance_use_status", "Smoking_freq_qy"],
    ["Substance_use_status", "Smoking_freq_sy"],
    ["Substance_use_status", "Smoking_type"],

    # Social Determinants of Health (SDOH)
    ["Abuse", "Sdoh_status"],
    ["Ethnicity", "Sdoh_status"],
    ["Financial_constrain", "Sdoh_status"],
    ["Gender", "Sdoh_status"],
    ["Living_Condition", "Sdoh_status"],
    ["Living_supply", "Sdoh_status"],
    ["Occupation", "Employment_status"],
    ["Physical_act", "Sdoh_freq"],
    ["Physical_act", "Sdoh_status"],
    ["Race", "Sdoh_status"],
    ["Sex_act", "Sdoh_status"],
    ["Social_cohesion", "Sdoh_freq"],
    ["Social_cohesion", "Sdoh_status"],
    ["Transportation", "Sdoh_status"],
]